# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=80)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('gravado', models.BooleanField(default=False)),
                ('upload', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=False)),
                ('descricao', models.CharField(blank=True, max_length=80)),
                ('comentario', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.FloatField(default=0)),
                ('planilha_quadro', models.BooleanField(default=False)),
                ('bonus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=80)),
                ('materia', models.CharField(blank=True, max_length=80)),
                ('categoria', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('inserido', models.BooleanField(default=False)),
                ('revisado', models.BooleanField(default=False)),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='code.Aula')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_modulo', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=80)),
                ('nome', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorTarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_contrato', models.DateTimeField()),
                ('previsao', models.DateTimeField()),
                ('data_entrega', models.DateTimeField(null=True)),
                ('prontos', models.BooleanField(default=False)),
                ('bonus', models.BooleanField(default=False)),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='code.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_video', models.IntegerField(default=0)),
                ('status_exercicio', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='modulo',
            name='exercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_exercicio', to='code.ProfessorTarefa'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='code.Status'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_video', to='code.ProfessorTarefa'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='tags',
            field=models.ManyToManyField(blank=True, to='code.Tag'),
        ),
        migrations.AddField(
            model_name='curso',
            name='modulos',
            field=models.ManyToManyField(blank=True, to='code.Modulo'),
        ),
        migrations.AddField(
            model_name='aula',
            name='bonus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='code.Bonus'),
        ),
        migrations.AddField(
            model_name='aula',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='code.Modulo'),
        ),
        migrations.AddField(
            model_name='aula',
            name='plataformas',
            field=models.ManyToManyField(blank=True, to='code.Plataforma'),
        ),
    ]
